version: "3"
services:      
  ngsild-broker:
    #build: .
    image: ngsi-broker
    container_name: "ngsild-broker"
    ports:
      - 8082:8082
    environment:
      - SERVER_PORT=8082
      - DEBUG=true
      - IDRA_BASEPATH=http://localhost:8080
#    networks:
#      - evitaNetwork 
       
#networks:
#  evitaNetwork:
#     driver: bridge