# server.port = 8082
# debug=true

## IDRA INFO ##
# idra.basepath=http://localhost:8080

server: 
  port: ${SERVER_PORT:8082}

debug: ${DEBUG:true}

idra:
  basepath: ${IDRA_BASEPATH:http://localhost:8080}
  
logging:
  level:
    '[org.springframework.web.client.RestTemplate]': ${LOG_LEVEL:DEBUG}